site_name: Papers, Please Beta Modding Documentation
site_author: marinesciencedude
repo_url: https://github.com/marinesciencedude/PapersPleaseModdingDoc
theme: readthedocs
nav:
    - Home: 'index.md'
    - XML:
        - _mod.ml: '_mod.md'
        - Bodies.xml: 'Bodies.md'
        - Emblems.xml: 'Emblems.md'
        - Faces.xml: 'Faces.md'
        - Intro.xml: 'Intro.md'
        - News.xml: 'News.md'