site_name: Papers, Please Beta Modding Documentation
site_author: marinesciencedude
repo_url: https://github.com/marinesciencedude/PapersPleaseModdingDoc
theme: readthedocs
nav:
    - Home: 'index.md'
    - XML:
        - _mod.xml: 'xml/_mod.md'
        - Bodies.xml: 'xml/Bodies.md'
        - Emblems.xml: 'xml/Emblems.md'
        - Faces.xml: 'xml/Faces.md'
        - Facts.xml: 'xml/Facts.md'
        - Intro.xml: 'xml/Intro.md'
        - News.xml: 'xml/News.md'
        - Papers.xml: 'xml/Papers.md'
    - TXT/CSV:
        - Days.csv: 'txt-csv/Days.md'
        - Errors.txt: 'txt-csv/Errors.md'
        - Speeches.txt: 'txt-csv/Speeches.md'
        - Travelers.txt: 'txt-csv/Travelers.md'
