site_name: Papers, Please Beta Modding Documentation
site_author: marinesciencedude
repo_url: https://github.com/marinesciencedude/PapersPleaseModdingDoc
theme: readthedocs
nav:
    - Home: 'index.md'
    - XML:
        - _mod.ml: 'docs/xml/_mod.md'
        - Bodies.xml: 'docs/xml/Bodies.md'
        - Emblems.xml: 'docs/xml/Emblems.md'
        - Faces.xml: 'docs/xml/Faces.md'
        - Intro.xml: 'docs/xml/Intro.md'
        - News.xml: 'docs/xml/News.md'